title = "Emily Ahn"
baseURL = "http://eahn01.github.io"
languageCode = "en-us"
theme = ["ananke"]
#resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Emily Ahn"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.fr]
    title = "Emily Ahn KR"
    weight = 2
    contentDir = "content/KR"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Mathemtics and Data Science student"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-washed-red"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/eahn01"
